---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags

  - name: lint
    image: golangci/golangci-lint:v1.42.1
    commands:
      - golangci-lint run --no-config -v --timeout 10m ./...
    when:
      event:
        exclude:
          - tag

  - name: release
    image: ghcr.io/goreleaser/goreleaser:v0.180.3
    commands:
      - goreleaser release --skip-announce
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      GOPROXY:
        from_secret: goproxy_url
    when:
      event: tag
